### ISSUE TITLE
Go get pulls the wrong version

### ISSUE THREAD

**Issue by hackthehackerman** [brandenc40/go-safer#2]
Hi Branden,

Thanks for open sourcing this project, I built a [crawler](https://github.com/hackthehackerman/safer_crawler) on top of it to scrape all safer data into a database. 

I want to report an issue that using `go get -u github.com/brandenc40/safer` will somehow download an older version (1.4). I think the latest tag `1.5` need to be changed to `v1.5.0` based on [this](https://go.dev/ref/mod#vcs-version). 

Again, thanks for opening sourcing the project!

**Comment by brandenco** [comment]
Thanks for flagging, this should be fixed now:

<img width="503" alt="Screen Shot 2022-10-31 at 3 25 38 PM" src="https://user-images.githubusercontent.com/37084158/199103624-89c948ae-23e3-4246-9a4d-e99a6d8d5073.png">

Awesome to see this is useful to someone else
